UKUK-Repository-Dept/ukuk-dspace

README.md

test jitka master

---

README.md

CI workflow

---

dspace/config/input-forms.xml

- Created new branch for input-forms.xml customizations and added reference to "articles" form to a new collection with handle ID 20.500.11956/103104.
- Minor fixes in element ordering according to input-forms.xml DTD file.
**This new branch should be used for making changes at input-forms.xml.**

Added reference to articles form to collection 20.500.11956/103104

---

dspace/config/input-forms.xml

List of new DSpace collections with "articles" form applied:
| handle | name | volume / issue |
| --------- | -------  | ------------------- |
| 20.500.11956/103461 | Studia Ethnologica Pragensia | 2018 / 1 |
| 20.500.11956/103605 | Studie z aplikované lingvistiky | 2018 / Specialní číslo |
| 20.500.11956/103732 | Chatreššar | 2018 / 1 |

Added articles input form to new collections of periodical issues

---

dspace/config/input-forms.xml

Applied to collections:
| handle | name | volume / issue |
| ------ | ---- | -------------- |
| 20.500.11956/103721 | Prague Papers on the history of int. relations | 2018/1 |
| 20.500.11956/103719 | Svět literatury | 2018/58 |

Added "articles" submit form to new collections

---

dspace/modules/xmlui-mirage2/src/main/webapp/themes/ukuk_theme/xsl/core/navigation.xsl

Links to english version of:
- UKAŽ
- ÚKUK library page
were added.

[Redmine-#55340] - Added links to english pages in 'Usefull links' part of right-side nav

---

dspace/config/input-forms.xml

Collection handle: 20.500.11956/105686

Added 'articles' form to new collection of Aesthetics journal 

---

dspace/modules/xmlui-mirage2/src/main/webapp/themes/ukuk_theme/xsl/core/page-structure.xsl

Added new contact e-mail to footer of DSpace webpage.

FIX: New contact e-mail in footer.

---

dspace/config/input-forms.xml

Added oa_books input form to OA Books collection

---

dspace/config/input-forms.xml

* Added 'articles' form to collections 20.500.11956/108696 and 20.500.11956/108698
* Added new form 'carolina_digi' to collection 123456789/23997 on test server

New collection input forms

---

dspace/config/modules/swordv2-server.cfg

DSpace will send e-mail notification when item enters workflow.

swordv2.notify changed back to false

---

dspace/config/input-forms.xml

'articles' input form added to collections identified by following handles:
* 20.500.11956/110927
* 20.500.11956/110563
* 20.500.11956/109919
* 20.500.11956/109920
* 20.500.11956/110564

Added 'articles' input form to new collections

---

dspace/config/input-forms.xml

with handles 20.500.11956/111563 & 20.500.11956/111497

Added 'articles' form to new collections

---

dspace/config/input-forms.xml

Added to collection with handle 20.500.11956/115624

Added articles input form to new collection

---

dspace/modules/additions/src/main/java/org/dspace/authenticate/UKShibAuthentication.java

Fixed return type of method isFromCU (shoud be boolean) + new code

---

dspace/config/input-forms.xml

of OA monographs of the Faculty of Law

Added 'oa_monographs' input form to new collection

---

dspace/config/item-submission.xml

* new submission type utilizes UploadFile step (without *embargo* functionality as it breaks the default access rights defined on the collection level)
* applicable for collections: [20.500.11956/108695](https://dspace.cuni.cz/handle/20.500.11956/108695) and [20.500.11956/116127](https://dspace.cuni.cz/handle/20.500.11956/116127) 
* these are collections for digitized study materials for *students with special needs*

Added new submission type

---

dspace/config/input-forms.xml

Added 'articles' input form to new collection

---

dspace/config/input-forms.xml

Used in special-digitization submission form.

Added RTF format as a valid file format for files in special digitization

---

dspace/modules/additions/src/main/java/org/dspace/authenticate/UKShibAuthentication.java
dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/ItemRequestForm.java
dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/eperson/AuthenticateAction.java
dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/eperson/LoginChooser.java
dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/eperson/Navigation.java
dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/eperson/ShibbolethAction.java

@jrihak Vyzkousejte tohle, nevim jestli to vyresi uplne vsechny use cases, ale tlacitko v pravem hornim rohu me vrati odkud jsem prisel. Zda se mi, ze funguje i pristup primo na soubor.
Tech zmen neni tolik, jen jsem soubory, ktere menim, presunul do modules (pokud tam jeste nebyly) - to je prvni commit. V druhem jsou pak zmeny samotne.

Login redirect

---

dspace/config/input-forms.xml

Collection handle: 20.500.11956/117320

Added 'articles' submission form to new collection 

---

dspace/config/input-forms.xml

Collection handle: 20.500.11956/118532

Added 'articles' input form to new collection 

---

dspace/config/input-forms.xml

Collection handles:
- 20.500.11956/120822
- 20.500.11956/120820

Added 'articles' form to new collections  

---

dspace/modules/xmlui-mirage2/src/main/webapp/themes/ukuk_theme/styles/uk-custom.css
dspace/modules/xmlui-mirage2/src/main/webapp/themes/ukuk_theme/xsl/aspect/artifactbrowser/item-view-theses-templates.xsl
dspace/modules/xmlui-mirage2/src/main/webapp/themes/ukuk_theme/xsl/aspect/discovery/discovery.xsl

...in collection item-list and discovery item-list

Standardized display order and text color for embargo information 

---

dspace/config/input-forms.xml

New collection HANDLE = 20.500.11956/123165

Added 'articles' form to new collection 

---

dspace/modules/xmlui-mirage2/src/main/webapp/themes/ukuk_theme/xsl/aspect/artifactbrowser/item-view-theses-templates.xsl

…otherwise this information will be inferred from grade

[defence-status] item-view: Added a template for using 'uk.thesis.defenceStatus' as a primary source of this information when available
